### ISSUE TITLE
To-Do's

### ISSUE THREAD

**Issue by dillonemorris** [elm-street-technology/stormquestions#1]
To-do:

### Hero section
- [x] Add contact form
- [x] Get video working
- [x] Add responsive styles

### Resources section
- [x] Add padding (should be same as "Why we're here" section)

### FAQ's section
- [x] Gather requirements (Are we adding "load more" functionality? If so, how many do we initially show?)

### Recommended Service Providers section
- [x] Style links according to mock
- [x] Add lineHeight to heading

### Blog section
- [x] Bring over blog from "Sites"
- [x] Add placeholder content for now 

### General
- [x] Add final CTA
- [x] Move header component to layout
- [x] Add Donate btn to header linking to GoFundMe

### Contentful
- [x] Wire up blog / blogList
- [x] Wire up blog tags
- [x] Double check individual posts
